MovieCenter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from apps.account.views import SiteLoginView, SiteSignupView
from django.conf.urls import handler404, url
from django.views.static import serve

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.core.urls")),
    path("movie/", include("apps.movie.urls")),
    path("cart/", include("apps.cart.urls")),
    path("checkout/", include("apps.checkout.urls")),

    path("account/", include("django.contrib.auth.urls")),
    path("account/", include("apps.account.urls")),
    path("login/", SiteLoginView.as_view(), name='login'),
    path("logout/", LogoutView.as_view(), name='logout'),
    path("signup/", SiteSignupView.as_view(), name='signup'),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    try:
        import debug_toolbar
        urlpatterns = [path("__debug__/",include(debug_toolbar.urls)),] + urlpatterns
    except ImportError:
        pass

handler404 = "apps.core.views.error404"

apps/cart/urls.py
from django.urls import path
from .views import CartDetailView, add_to_cart, remove_from_cart

app_name = "cart"

urlpatterns = [
    path("", CartDetailView.as_view(), name="cart"),
    path("add/<slug>/", add_to_cart, name="add-to-cart"),
    path("remove/<slug>/", remove_from_cart, name="remove-from-cart"),
]

apps/core/urls.py
from django.urls import path
from .views import AboutView, ContactView, HomeListView

app_name = "core"

urlpatterns = [
    path("", HomeListView.as_view(), name="home"),
    path("about/", AboutView.as_view(), name="about"),
    path("contact/", ContactView.as_view(), name="contact"),
]

apps/movie/urls.py
from django.urls import path
from .views import MovieDetailView, MovieListView, SearchMovie
from .models import Movie

app_name = "movie"

urlpatterns = [
    path("all/", MovieListView.as_view(model=Movie), name="movie-list"),
    path("<slug:the_slug>", MovieDetailView.as_view(), name="movie-detail"),
    path("search/", SearchMovie.as_view(), name="search-movie"),
]

apps/movie/models.py
from django.db import models
from django.utils.text import slugify
from django.shortcuts import reverse


class Actor(models.Model):
    name = models.CharField(max_length=30)
    photo = models.ImageField(upload_to="actor_photo/", blank=True)

    def __str__(self):
        return self.name


class Movie(models.Model):
    title = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=9, decimal_places=2)
    director = models.CharField(max_length=30)
    actors = models.ManyToManyField(Actor)
    genres = models.CharField(max_length=100)
    country = models.CharField(max_length=5)
    year = models.CharField(max_length=4)
    imdb_score = models.DecimalField(max_digits=9, decimal_places=2)
    imdb_link = models.URLField(default="")
    trailer = models.URLField(default="", null=True)
    description = models.TextField()
    slug = models.SlugField(default="", unique=True)
    is_active = models.BooleanField(default=True)
    poster = models.ImageField(upload_to="movie_poster/", blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Movie, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("movie-detail", kwargs={"slug": self.slug})

    def get_add_to_cart_url(self):
        return reverse("cart:add-to-cart", kwargs={"slug": self.slug})

    def get_remove_from_cart_url(self):
        return reverse("cart:remove-from-cart", kwargs={"slug": self.slug})

apps/templates/includes/footer.html
<style>
    #edit {
        text-align: center;
        top: 50%;
        background-color: #1f1f1f;
        color: white;
    }

    .footer {

        left: 0;
        margin-bottom: 0;
        width: 100%;
        color: white;
        text-align: center;
        height: 250px;
        padding: 20px;
    }

    #contact {
        margin: 15px;
    }

    #contact a {
        margin-right: 10px;
        color: #fff;
    }

    #contact a:hover {
        color: #E29635;
    }

    #final-text {
        margin-bottom: 0px !important;
    }

    .row {
        padding-top: 50px;
        padding-bottom: 0;
    }

</style>

<div class="row welcome">
    <div class="col-12 footer sticky-bottom">
        <div id="edit">
            <br>
            <br>
            {% comment %} eKINO {% endcomment %}
            <img src="/static/img/logo-default.png"><br>
            <a href="/login"><img src="/static/img/baner.png"></a>
            <br>
            <div id="contact">
                <a href="#"><i class="fab fa-facebook-f"></i></a>
                <a href="#"><i class="fab fa-twitter"></i></a>
                <a href="#"><i class="far fa-compass"></i></a>
                <a href="#"><i class="far fa-heart"></i></a>
                <a href="#"><i class="far fa-smile"></i></a>
                <a href="#"><i class="far fa-thumbs-up"></i></a>
                <br>
                <br>
                <p id="final-text">2021 All Rights Reserved Terms of Use</p>
                <p>Obrazki użyte na stronie wyłącznie w celach wizualizacji.
                Kopiowanie i rozpowszechnianie zabronione.</p>
            </div> <!-- contact -->
        </div> <!-- EDIT -->
        <br>
    </div>
</div> <!-- col-12 footer sticky-bottom -->

apps/templates/includes/navbar.html
<style>
  * {
    box-sizing: border-box;
  font-family: 'Poppins', sans-serif;
  }


  html,
  body {
    width: 100%;
    background-color: #1f1f1f;
    color: white;
    max-width: 1920px;
    margin: 0 auto;
  }

  .navbar {
    height: 87px;
  }

  .container{
  min-width: 70%;
  max-height: 100%;
  margin: 0 auto;
  }

  .navbar li {
    margin-right: 21px;
    list-style-type: none;
  }

  .navbar li a {
    color: #fff;
  }
  .navbar li a:hover {

    color: #E29635;
    transition: 0.3s;
  }

  .header-nav {
    position: relative;
    left: 65%;
    font-size: 14px;
    line-height: 21px;
  }
  .header-nav:before,
  .header-nav:after {
    content: "";
    display: table;
  }
  .header-nav:after {
    clear: both;
  }

  .menu {
    display: inline-block;
    list-style-type: none;
    margin: 0;
    padding: 0;
  }
  .menu li {
    display: inline-block;
  }
  .menu li a {
    display: block;
    position: relative;
    transition: 0.3s;
    text-decoration: none;
  }

  .search-button {
    position: absolute;
    right: -65%;
    top: 50%;
    height: 44px;
    width: 267px;
    transform: translate(0, -50%);
    z-index: 999;
    border-radius: 4vh;
    border: 1px solid #E29635;
  }

  .search-toggle {
    position: relative;
    top: 40%;
    right: -85%;
    display: block;
    height: 14px;
    width: 14px;
    color: #fff;
  }
  .search-toggle::before,
  .search-toggle::after {
    content: "";
    position: absolute;
    display: block;
    transition: all 0.1s;
  }
  .search-toggle::before {
    border: 2px solid #E29534;
    border-radius: 50%;
    width: 100%;
    height: 100%;
    left: -2px;
    top: -2px;
  }
  .search-toggle::after {
    height: 2px;
    width: 9px;
    background: #E29534;
    top: 10px;
    left: 8px;
    transform: rotate(45deg);
  }
  .search-toggle.active::before {
    width: 0;
    border-width: 1px;
    border-radius: 0;
    transform: rotate(45deg);
    top: -2px;
    left: 4px;
  }
  .search-toggle.active::after {
    width: 14px;
    left: -2px;
    top: 4px;
  }

  #header-1 .search-box {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    max-height: 0;
    transform: translate(50%, 0);
    background-color: transparent;
    transition: all 0.3s;
    z-index: 999;
  }


  #header-1 .search-box .search-input {
  position: absolute;
  top: 5%;
  left: 65%;
  width: 40%;
  height: 100%;
  padding: 1.5em 1em;
  background-color: transparent;
  opacity: 1;
  padding-left: 15px;
  border-color: transparent;
  outline: none;
  color: white;
}
  }
  #header-1.show .search-box {
    max-height: 40px;
  }
  #header-1.show .search-box .search-input {
    opacity: 1;
  }





  /*------------------------------------------*/




  .dropdown {
    position: relative;
    display: inline-block;
  }

  /*sub-menu*/
  .dropdown-menu {
    display: none;
    position: absolute;
    width: 100%;
    background: #1f1f1f;
    margin-top: auto;
    top: 100%;
    z-index: 999;
<!--    border-radius: 4vh;-->
    text-decoration: none;
    transition: all 0.1s 0.1s ease-in;
    -moz-transition: all 0.1s 0.1s ease-in;
    -webkit-transition: all 0.1s 0.1s ease-in;
  }
  .dropdown:hover .dropdown-menu {
    display: block;
    text-decoration: none;
        color: #E29635;
  }

  .dropdown-item:focus,
  .dropdown-item:hover {
    height: auto !important;
        color: #E29635;
        border-radius: 4vh;
  }



</style>

<header>
  <!-- new Navbar -->
  <nav class="navbar navbar-expand-md sticky-top">
    <div id="menuTop" class="container">
      <a class="navbar-branch" href="/">
        <img src="/static/img/logo-default.png"/>
      </a>
<!--      <button-->
<!--        class="navbar-toggler collapsed"-->
<!--        aria-expanded="false"-->
<!--        aria-controls="navbarExample01"-->
<!--        aria-label="Toggle navigation"-->
<!--        type="button"-->
<!--        data-target="#navbarsExample01"-->
<!--        data-toggle="collapse"-->
<!--      >-->
<!--        <span class="navbar-toggler-icon"></span>-->
<!--      </button>-->
      <div class="navbar-collapse collapse" id="navbarExample01">
        <header id="header-1" class="header">
          <nav class="header-nav">
            <div class="search-button">
              <a href="#" class="search-toggle" data-selector="#header-1"></a>
            </div>
            <ul class="navbar-nav ml-auto menu">
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'core:home' %}"><span class="iconsHeader" style="font-size: 18px;">⌂</span> Strona główna</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'movie:movie-list' %}"><span class="iconsHeader" style="font-size: 18px;">⚅</span> Filmy i seriale</a>
              </li>
<!--              <li class="nav-item">-->
<!--                <a class="nav-link" href="{% url 'core:about' %}">☺ O nas</a>-->
<!--              </li>-->
<!--              <li class="nav-item">-->
<!--              <a class="nav-link" href="{% url 'core:contact' %}">☏ Kontakt</a>-->
<!--             </li>-->

              {% if user.is_authenticated %}
              <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                <a class="list-item" href="{% url 'cart:cart' %}">
                  <i class="fas fa-shopping-cart"></i> Koszyk</a>
              </li>
<!--              <input type="text" placeholder="co dzisiaj oglądamy?" style=" border-radius: 4vh;-->
<!--    border-color: #E29635; font-size: 16px; padding-left: 10px;">-->
              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  data-toggle="dropdown"
                  id="SearchButton"><i class="fas fa-user-circle"></i> {{ user.username }}
                </a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="/account/profile"
                    >Aktualizuj profil</a
                  >
                  <a class="dropdown-item" href="{% url 'logout' %}"
                    >Wypisz się</a
                  >
                </div>
              </li>
              {% else %}
              <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                <a class="list-item" href="{% url 'login' %}">
                  <i class="fas fa-shopping-cart"></i> Koszyk</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}"><i class="fas fa-user-circle"></i> Logowanie</a>
              </li>
              {% endif %}
            </ul>
            <form
              method="GET"
              action="{% url 'movie:search-movie' %}"
              class="search-box"
              style="color: white;"

            >
              <input
                type="text"
                class="search-input"
                style="border: none; color: white;"
                name="movie_name"
                type="text"
                placeholder="Co dzisiaj oglądamy?"
                autocomplete="off"
                value="{{ request.GET.search }}"
              />
            </form>
          </nav>
        </header>
      </div>
    </div>
  </nav>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"
  ></script>
  <script type="text/javascript">
$(".header").on("click",".search-toggle",function(e){
var selector = $(this).data("selector");
$(selector).toggleClass("show").find(".search-input").focus();
$(this).toggleClass("active")
e.preventDefault();
});
  </script>
</header>

apps/templates/includes/searchForm.html
<style>

.searchMovies{
width: 70%;
height: 25vh;
background-color: #1f1f1f;
margin: 0 auto;
}

h5{
padding: 30px 0 0 30px;

}

form{
width: 100%;
padding: 10px 30px;
}

    .upperInput,
    .lowerInput
    {
    width: 100%;
    background-color: white;
    border-radius: 4vh;
    border-color: #E29635;
    border: 2px solid #E29635;
    margin-top: 5px;

    }

    .lowerInput{
        background-color: transparent;
        width: 100%;
        border: none;
    }

    .upperInput input,
    .lowerInput input{
    background-color: transparent;
    padding: 5px 8px;
    border-width: 0;
    text-align: left;
           opacity: 1;
       color: black;
    }

    .upperInput input::placeholder{
    padding-right: 10px;
    width: 100%;

    }

    .upperInput input:focus,
    .lowerInput input:focus{
       outline: none;
       border: none;
       opacity: 1;
       color: black;
    }

    .lowerInput{
    display: flex;
    flex-direction: row;
flex-wrap: no-wrap;
justify-content: flex-start;
align-items: center;
align-content: center;
    }

    .firstInput,
    .secondInput,
    .thirdInput{
    position: relative;
    width: 35%;
    background-color: white;
    border-radius: 4vh;
    border-color: #E29635;
    border: 2px solid #E29635;
    outline: none;
    text-align: left;
    margin-left: 25px;
    padding-left: 5px;
    }

    .firstInput{
    margin-left:0;
    }

    .lowerInput select{
border: none;
width: 95%;
}


    .lowerInput .fas{
    position: absolute;
    top:25%;
    right: 5%;
    }


    div.btnSearchMain{
    width: 97%;
    text-align: center;
    }



.btnSearch{
border-radius: 4vh;
background: rgb(255,200,53);
background: linear-gradient(135deg, rgba(255,200,53,1) 0%, rgba(226,150,53,1) 100%);
padding: 10px 40px;
width: 20%;
margin-top: 20px;
    text-decoration: none;
    color: #1f1f1f;
    border: none;
}


</style>
<script type="text/javascript">
$(".header").on("click",".search-toggle",function(e){
var selector = $(this).data("selector");
$(selector).toggleClass("show").find(".search-input").focus();
$(this).toggleClass("active")
e.preventDefault();
});
</script>

<div class="col-12">

<div class="searchMovies" style="margin-top: 50px;">

    <h5>Szukaj filmów:</h5>

    <form action="{% url 'movie:search-movie' %}">
        <div class="upperInput">
            <input  type="text"
                class="search-input"

                name="movie_name"
                type="text"
                placeholder="Co dzisiaj oglądamy?"
                value="{{ request.GET.search }}">
        </div>
        <div class="lowerInput">
            <div class="firstInput">
                <select id="gatunek" name="gatunek">
                 {% for movie in movie_list %}
                    <option value="{{ movie.genres }}">{{ movie.genres }}</option>
                {% endfor %}
                       </select>
                </div>


            <div class="secondInput">
                <select id="data" name="data">
                 {% for movie in movie_list %}
                    <option name="{{ movie.year }}">{{ movie.year }}</option>
                {% endfor %}
                       </select>
            </div>
            <div class="thirdInput">
                <select id="kraj" name="kraj">
                 {% for movie in movie_list %}
                    <option name="{{ movie.country }}">{{ movie.country }}</option>
                {% endfor %}
                       </select>
            </div>
        </div>
            <div class="btnSearchMain"><button class="btnSearch">szukaj</button></div>
    </form>


</div>

    </div>